### ISSUE TITLE
Program isn't running. 

### ISSUE THREAD

**Issue by CoryMedina** [C-HGP/GPTalk#1]
Hello, I'm new to coding and I'm wanting to try and use this, but it seems to give me an issue. I'm using visual studio code and I have python installed, I've downloaded the repository and have it imported into visual studio code, but when I run the code, it gives me the following message: 

PS C:\Users\Admin\Desktop\GPTalk-main\GPTalk-main> & C:/Users/Admin/AppData/Local/Programs/Python/Python311/python.exe c:/Users/Admin/Desktop/GPTalk-main/GPTalk-main/smart_speaker.py
  File "c:\Users\Admin\Desktop\GPTalk-main\GPTalk-main\smart_speaker.py", line 2
    pip install -r requirements.txt
        ^^^^^^^
SyntaxError: invalid syntax

I think it's referring to the "pip install -r requirements.txt" as it's underlined in red.

Sorry if there is an obvious solution, I tried looking into it and solving it myself, but I can't seem to find a solution. Any help would be appreciated.

**Comment by C-HGP** [comment]
Hi Cory!

Welcome to the world of programming.

I have updated the script with a new library and a new readme on what needs to be done. 
However, the error message suggests that you are trying to execute the smart_speaker.py file using the Python interpreter, but the second line of the file contains the command pip install -r requirements.txt, which is not a valid Python syntax.

The pip install -r requirements.txt command is usually used to install the required packages and dependencies for a Python project. It needs to be executed in the terminal or command prompt, not inside a Python file.

To fix the error, you should run the pip install -r requirements.txt command in your terminal or command prompt first, then run the smart_speaker.py file again. Alternatively, you can remove the pip install -r requirements.txt command from the smart_speaker.py file if the required packages have already been installed.

**Comment by C-HGP** [comment]
Please note though, that i'm actively developing this, so bugs and issues is likely! :)

**Comment by CoryMedina** [comment]
No worries, thank you for the quick response, I really appreciate it. I
tried running the pip install -r requirements.txt within the terminal and
it gave me this message:

pip : The term 'pip' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try
again.
At line:1 char:1
+ pip install -r requirements.txt
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [],
CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


And so I also tried running the code even though I got pip install
error and got this message:


PS C:\Users\Admin\Desktop\GPTalk-main (1)> &
C:/Users/Admin/AppData/Local/Programs/Python/Python311/python.exe
"c:/Users/Admin/Desktop/GPTalk-main (1)/GPTalk-main/smart_speaker.py"
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\GPTalk-main
(1)\GPTalk-main\smart_speaker.py", line 1, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'


I'm assuming that just because I don't have the requirements installed.

Also sorry I'm sending all these errors your way as if you're supposed to
solve them, I don't want to annoy you with these problems as I know
development takes time, and or these might be simple issues. I'm just a bit
oblivious to what needs to be done, but If need be I can give it some time
and check back in a while.

**Comment by C-HGP** [comment]
No worries, only happy to help out!

It looks like you are encountering a few issues while trying to install the requirements for the project. Let me try to help you out.

Firstly, the error message you received when running `pip install -r requirements.txt` suggests that `pip` is not recognized as a valid command. This might be because Python is not added to your system PATH environment variable. To resolve this issue, you can try specifying the full path to the pip executable like this: `python -m pip install -r requirements.txt`. This will make sure that you are using the pip executable that is associated with the Python installation you are using.

Secondly, the error message you received when running `smart_speaker.py` suggests that the `openai` module is not installed. To install it, you can use `pip` again like this: `python -m pip install openai`. Make sure to run this command after resolving the first issue.

I hope this helps you resolve your issues. Let me know if you have any further questions or encounter any more issues.

**Comment by C-HGP** [comment]
Also, make sure you have the latest version of the project after my latest update by running `git pull`  in the project directory. 
Or re-download the .zip file from the project.

**Comment by CoryMedina** [comment]
Hey, I'm having a similar problem still, now I made sure to see if my
python was up to date and that it was installed properly, and I'm sure it
is. But when I run the "pip install -r requirements.txt" in the terminal it
gives this error:

PS C:\Users\Admin> python -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not
writeable
ERROR: Could not open requirements file: [Errno 2] No such file or
directory: 'requirements.txt'

Now I know you mentioned to specify the path to it in your last response
but I'm not really sure how to do that. I've only spent maybe a few hours
the past 2 days trying to figure it out on my own but I still don't really
know what to do.


I've tried to install the requirement on their own by typing "pip install
speech_recognition" but it give me this message:

PS C:\Users\Admin> pip install speech_recognition
Defaulting to user installation because normal site-packages is not
writeable
ERROR: Could not find a version that satisfies the requirement
speech_recognition (from versions: none)
ERROR: No matching distribution found for speech_recognition

It says "from versions: none" does that mean I don't have it at all? Are
there seperate software,  plugin or tools that I need to install besides
just python?


Also could you explain what changing the directory means? In step two in
the readme it mentions:
2. Change the directory:
cd GPTalk

Is that a command to run in the terminal?


I'm now thinking that trying to jump into programming with no
prior knowledge by starting off with what seems to be a complex system,
wasn't the best idea. But the utilization of ChatGPT and being able to
develop tools like this is something that really interests me. If you could
help set this up properly I would very much appreciate it. Or maybe give me
a direction to trying to solve the issues I'm facing. Either way, any help
would be greatly appreciated.

**Comment by CoryMedina** [comment]
I've also made sure to redownload the .zip from the Github project.

**Comment by CoryMedina** [comment]
Wait actually i think i resolved the importing for the requirements, I think i just need to get porcupine now.

**Comment by CoryMedina** [comment]
Okay so I think I did all the steps correctly, but now when I try to run the program it gives me this error message. 

PS C:\Users\Admin\Desktop\GPTalk-main> & "C:/Program Files/Python311/python.exe" c:/Users/Admin/Desktop/GPTalk-main/GPTalk-main/smart_speaker.py
  File "c:\Users\Admin\Desktop\GPTalk-main\GPTalk-main\smart_speaker.py", line 80
    keyword_path = "C:\Users\Admin\Desktop\Hey-jake_en_windows_v2_2_0.ppn"
                                                                          ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
PS C:\Users\Admin\Desktop\GPTalk-main> 


One other thing to mention is that the "from pvporcupine import Porcupine" the "pvporcupine" still has a yellow squiggly line under it. Do that mean I still need to install something else?

**Comment by CoryMedina** [comment]
Okay well now I figure out how to solve the unicode error.  So, scratch that.

The only issue it's giving me is the "from pvporcupine import Porcupine" 

It states "ModuleNotFoundError: No module named 'pvporcupine'" 

How do I resolve this?

**Comment by CoryMedina** [comment]
Okay never mind i resolved that issue with the pvporcupine. 

But now I think i'm having an error with my open-ai key. When i run the program, it just says the following:

PS C:\Users\Admin\Desktop\GPTalk-main> & "C:/Program Files/Python311/python.exe" c:/Users/Admin/Desktop/GPTalk-main/GPTalk-main/smart_speaker.py
("open-ai key") 

and in the brackets where is says ("open-ai key), it doesn't say that in the program, in the program it is my actual key, i just removed it here. 

How do I know if the program is running correctly? Is this an issue?

**Comment by CoryMedina** [comment]
Okay never mind again, I solved that issue. 

When I run it i now here "welcome to GPTalk" but I'm now getting this error: 

PS C:\Users\Admin\Desktop\GPTalk-main> & "C:/Program Files/Python311/python.exe" c:/Users/Admin/Desktop/GPTalk-main/GPTalk-main/smart_speaker.py
[ERROR] failed to parse AccessKey '& "C:/Program Files/Python311/python.exe" c:/Users/Admin/Desktop/GPTalk-main/GPTalk-main/smart_speaker.py'
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\GPTalk-main\GPTalk-main\smart_speaker.py", line 146, in <module>
    main()
  File "c:\Users\Admin\Desktop\GPTalk-main\GPTalk-main\smart_speaker.py", line 93, in main
    porcupine = Porcupine(
                ^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineInvalidArgumentError
PS C:\Users\Admin\Desktop\GPTalk-main> 


I see that it mentions something about failing to parse access key, in which honestly I have no idea what issue could lie there. But also that there's this as well: 


File "C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineInvalidArgumentError

And as well I have no idea what that could mean.

**Comment by CoryMedina** [comment]
Okay Strach everything, I figured it out and it's working normally now. So sorry for the spam if you get notifications for all of the comments.  

I was trying to figure things out! But I got it working now!

Though one question, how would i change the voice to a different one, the voice that is speaking is a bit robotic and Id like to have one that would a bit smoother. If you know how and could let me know that would be great. 

Thanks!

**Comment by C-HGP** [comment]
Hi @CoryMedina

Good job on resolving your issues, thats the best way to go!

Currently I use a really basic text2speech library which sounds very inhuman and robotic, like you say.
Onward, i'm looking to implement something like ElevenLabs for the speaker voice. Could be a good start for you to work with.

So, if you want to, before I have a chance to work on it, try implementing ElevenLabs API into the script and create a pull request towards the project!

**Comment by CoryMedina** [comment]
Hey, it's been a little bit and I'm still trying to figure out where to kind of get started with programing. I know this might be a little much to ask, especially since we don't even know each other, but I was wondering if I could pick your brain for a little bit and just ask some questions. 

As there are a few specific applications I want to try and build towards to actually having them as functioning programs, but I honestly have no idea where to start or if the things I think I should be looking into are even relevant to what I'm trying to build. So, if your open to it, if I could just shoot you a bunch of questions and if you could answer to the best of your ability that would be beyond amazing. 

As you're the only person I've ever talked to that already knows how to program. 

Also, if you don't want to no worries, seriously, I just thought it would be worth an ask since maybe you could give me a better direction on where to go. But again, no worries if you don't want to. 

Let me know! 

Thanks!

**Comment by C-HGP** [comment]
Hi @CoryMedina 

Sure, I'll help you out. 
If you want, instead of discussing this on a Github issue, you can contact me on Discord. My name is: "CHP#0369" or shoot me an email at "carl@athlas.io".

Best,

**Comment by CoryMedina** [comment]
Great! Thanks a lot, I really applicate it, I sent you a friend request on Discord. My Discord name is Cory
